baseURL = "https://gsepe-dev.github.io/"
defaultContentLanguage = "it"
enableRobotsTXT = true
languageCode = "it"
theme = "gokarna"
title = "Sepe Gennaro"

[params]
  avatarURL = "/avatar.jpg"
  avatarAltText = "avatar"
  avatarSize = "size-m"
  dateFormat = "2 January 2006"
  description = "Benvenuti nel mio angolo di cinema, dove ogni film diventa una storia da raccontare e un'emozione da condividere."
  footer = " "
  metaKeywords = ["blog", "gokarna", "hugo", "gsepe-dev", "gsepe"]  
  showBackToTopButton = true
  togglePreviousAndNextButtons = true
  displayReadingTime = false
  
[minify]
  minifyOutput = true  
    
[menu]
  [[menu.main]]
    name = "Recensioni"
    pre = "<span data-feather='book'></span>"
    url = "/reviews/"
    weight = 1
    
  [[menu.main]]
    name = "FAQ"
    pre = "<span data-feather='info'></span>"
    url = "/info"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/gsepe-dev"
    weight = 3
    pre = "<span data-feather='github'></span>"
    post = ""

